[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "calendar-app"
version = "0.0.1"
dependencies = [
	"fastapi",
	"hypercorn",
	"icalendar",
]

[tool.optional-dependencies]
dev = [
	"pytest",
]

